#!/bin/bash

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

UNICORN=/usr/local/bin/unicorn
KILL=/bin/kill
APP_ROOT=/usr/share/nginx/slc.io
PID=$APP_ROOT/tmp/pids/unicorn.pid
GEM_HOME=/var/lib/gems/1.9.1/gems/

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

case "$1" in
        start)
                echo "Starting unicorn..."
                cd $APP_ROOT
                $UNICORN -D -E production -c unicorn.conf
                ;;
        stop)
                sig QUIT && exit 0
                echo >&2 "Not running"
                ;;
        restart)
                $0 stop
                $0 start
                ;;
        status)
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                ;;
esac
